//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingHoteSystemlWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Branch
    {
        public int ID { get; set; }
        public string Branch_loca { get; set; }
        public Nullable<int> HGuest_id { get; set; }
        public Nullable<int> HRoom_number { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
    }
}
