//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingHoteSystemlWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Hotel_Branch = new HashSet<Hotel_Branch>();
        }
    
        public int Room_number { get; set; }
        public string Room_loca { get; set; }
        public Nullable<int> Guest_id { get; set; }
        public string Room_type { get; set; }
        public Nullable<bool> Room_status { get; set; }
        public Nullable<System.DateTime> Room_Date { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Guest Guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_Branch> Hotel_Branch { get; set; }
    }
}
